### PR TITLE
Update xha-10.1.0-support-drbd.XCP-ng.patch patch (improvements + fixes)

### PR DESCRIPTION
**Pull request by Wescoeur**
Koji build: http://koji.xcp-ng.org/taskinfo?taskID=18593

### CODE REVIEW

**Comment by Wescoeur** [comment]
Before merge it would be interesting to implement XHA auto-tests and try if these changes are compatible with other SRs.
So: WIP for the moment.

**Comment by Wescoeur** [comment]
Koji build: http://koji.xcp-ng.org/taskinfo?taskID=19536

**Review by benjamreis — APPROVED** [review]

**Comment by stormi** [comment]
Since we can't rely on the patch description to understand what was changed from the previous iteration of the same patch, it would be good to describe the changes that were made in the commit message (the usual information: why the change is needed and what is changed - without assuming that one will read the code when going through the git history).

About merge status, I don't know yet when we'll merge exactly. Current target is end of the linstor driver beta.

**Review by benjamreis — APPROVED** [review]

**Comment by Wescoeur** [comment]
I created a new branch (8.2-linstor), so this PR is not useful now.

**Pull request closed without merging**
